import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import UserProfile from "./auth/user/userProfile";
import { cookies } from "next/headers";
import { getSession } from "@/lib/session";
import { AppProvider } from "@/lib/isConnectedContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const sessionId = cookieStore.get("session-id")?.value;

  const session = sessionId ? await getSession(sessionId) : null;
  console.log("Session in the middleware:", session);
  const isLoggedIn = !!session;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AppProvider>
            {isLoggedIn ? <UserProfile /> : null}
            {children}
          </AppProvider>
        </Providers>
      </body>
    </html>
  );
}
